default_environment: us_nestlon
environments:
    us_nestlon:
        connections:
            duckdb:
                - name: duckdb-default
                  path: outputs/us_nestlon/pipeline.duckdb
    us_modularity:
        connections:
            duckdb:
                - name: duckdb-default
                  path: outputs/us_modularity/pipeline.duckdb
